development:
  clients:
    default:
      database: op2_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: op2_development
      hosts:
        - localhost:27017