development:
  clients:
    default:
      database: qualimed_hospitals
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: qualimed_hospitals
      hosts:
        - localhost:27017
