development:
  sessions:
    default:
      database: op2_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: op2_development
      hosts:
        - localhost:27017