development:
  clients:
    default:
      database: qualimed_hospitals
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: qualimed_hospitals
      hosts:
        - localhost:27017