development:
  sessions:
    default:
      database: mongoid_test_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: mongoid_test_development
      hosts:
        - localhost:27017